version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_web
    volumes:
    - .:/app  # <-- monta todo o projeto local dentro do container
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy  # Só inicia depois que o db estiver saudável

  db:
    image: postgres:15
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: #  garante que só fica "healthy" depois de pronto
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5   

  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
